version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fastapi_backend
    env_file:
      - .env
    environment:
      - IS_DOCKER=1
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "sleep 5 && python -m db.dbmigrations && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:
